# Generated by Django 3.2.16 on 2022-10-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('short_name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('funded_date', models.DateField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.country')),
            ],
        ),
    ]
